# nivel de concurrencia
nthreads: 16

# ficheros
ultimas: ../data/calidad-aguas.csv # ultimas mediciones
historico: ../data/calidad-aguas-historico.csv # historico de mediciones
crowdsourcing: ../data/calidad-aguas-parcial-gdocs.csv # crowdsourcing google docs
log: ../data/nayade.log # log
